language: node_js
git:
  depth: 1
node_js:
- '10'
cache:
  directories:
  - node_modules
install:
- npm install --force
script:
- npm test
- npm run eslint
- npm run stylelint
deploy:
  provider: npm
  email: planxcyborg@gmail.com
  api_key:
    secure: XGDwmt5fyVD6NVq1AcKcSlyNc9JQJlqIMhWZRvGc0lvjNmpIH3mZsCyjCh8OgYQkixkNC+m0dKJKhIIEfwjDH1hlhukcuQFAASeL6Jz0Tha5W6OqeCwIeIcKm72EJSSPUAT4c0CMgghfSZjqUei5RxJM2wZ/xFpW98M3bIBoAp8OVOFxPjQlIOK35ceEiJ+czqluhswKDpvev1cwIcQ08Yw7aljqx+VNcjv4IfU7Hd035Wy9L6EM3aq+A3sxj93zSS0Jcn09wSvBh9yRap/EdjizKW0GE45PwzLGzXKRWo69EUTd1+iQ37kmBJGrx/v52AIfAKl7JJcvKQUT38ov5F+P0AhxaGpxawKYnhddkJ9VnfWBo2Jgj7qRnf0LSXf8fPDsPAMKOFRGbsCzGdLcpT/PzTvVZNgiskuckY29Wmo+82MEptlGbaBZfYUMkUSMmtPLDac765nUEUlEnE+nxlwi2l5NRNQ5OmIyW2ZtvUSysdOU8IluUpbjZ8rhP9Ojbi8Yp3jeUc2aCLTeT1/c4t0Cq3mUxLnVJnHi7u/OGT/ery6LO35imMEfCBT6bmQtYTW4Dde9Fmy62lUa82yA3C0hYngUmJioE5qIomn23jXM9TataqnYnaWAIqkLMetO4nuGkZbTvCxBGoM71NJJXpROiEOmVt9H+14mNcYM9Cw=
  skip_cleanup: true
  on:
    repo: uc-cdis/gen3-ui-component
    branch: master
